import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', title: 'Dashboard — Kubsome', loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'monitor', title: 'Monitor — Kubsome', loadComponent: () => import('./features/monitor/monitor.component').then(m => m.MonitorComponent) },
  { path: 'pods', title: 'Pods — Kubsome', loadComponent: () => import('./features/pods/pods.component').then(m => m.PodsComponent) },
  { path: 'events', title: 'Events — Kubsome', loadComponent: () => import('./features/events/events.component').then(m => m.EventsComponent) },
  { path: 'metrics', title: 'Metrics — Kubsome', loadComponent: () => import('./features/metrics/metrics.component').then(m => m.MetricsComponent) },
  { path: 'deployments', title: 'Deployments — Kubsome', loadComponent: () => import('./features/deployments/deployments.component').then(m => m.DeploymentsComponent) },
  { path: 'logs', title: 'Logs — Kubsome', loadComponent: () => import('./features/logs/logs.component').then(m => m.LogsComponent) },
  { path: 'jobs', title: 'Jobs — Kubsome', loadComponent: () => import('./features/jobs/jobs.component').then(m => m.JobsComponent) },
  { path: 'namespace', title: 'Namespace — Kubsome', loadComponent: () => import('./features/namespace/namespace.component').then(m => m.NamespaceComponent) },
  { path: 'rbac', title: 'RBAC — Kubsome', loadComponent: () => import('./features/rbac/rbac.component').then(m => m.RbacComponent) },
  { path: 'network', title: 'Network — Kubsome', loadComponent: () => import('./features/network/network.component').then(m => m.NetworkComponent) },
  { path: 'secrets', title: 'Pull Secrets — Kubsome', loadComponent: () => import('./features/secrets/secrets.component').then(m => m.SecretsComponent) },
  { path: 'incident', title: 'Incident — Kubsome', loadComponent: () => import('./features/incident/incident.component').then(m => m.IncidentComponent) },
  { path: 'graph', title: 'Service Map — Kubsome', loadComponent: () => import('./features/graph/graph.component').then(m => m.GraphComponent) },
  { path: 'yaml', title: 'YAML Editor — Kubsome', loadComponent: () => import('./features/yaml-editor/yaml-editor.component').then(m => m.YamlEditorComponent) },
  { path: 'settings', title: 'Settings — Kubsome', loadComponent: () => import('./features/settings/settings.component').then(m => m.SettingsComponent) },
  { path: 'compare', title: 'Compare — Kubsome', loadComponent: () => import('./features/compare/compare.component').then(m => m.CompareComponent) },
  { path: 'timeline', title: 'Timeline — Kubsome', loadComponent: () => import('./features/timeline/timeline.component').then(m => m.TimelineComponent) },
  { path: 'cost', title: 'Optimization — Kubsome', loadComponent: () => import('./features/cost/cost.component').then(m => m.CostComponent) },
  { path: 'runbooks', title: 'Runbooks — Kubsome', loadComponent: () => import('./features/runbooks/runbooks.component').then(m => m.RunbooksComponent) },
  { path: 'search', title: 'Search — Kubsome', loadComponent: () => import('./features/search/search.component').then(m => m.SearchComponent) },
  { path: 'ai', title: 'AI Assistant — Kubsome', loadComponent: () => import('./features/ai/ai.component').then(m => m.AiComponent) },
  { path: 'terminal', title: 'Terminal — Kubsome', loadComponent: () => import('./features/terminal/terminal.component').then(m => m.TerminalComponent) },
  { path: 'resources', title: 'Resources — Kubsome', loadComponent: () => import('./features/resources/resources.component').then(m => m.ResourcesComponent) },
  { path: 'scorecard', title: 'Scorecard — Kubsome', loadComponent: () => import('./features/scorecard/scorecard.component').then(m => m.ScorecardComponent) },
  { path: 'cost-estimate', title: 'Cost Estimate — Kubsome', loadComponent: () => import('./features/cost-estimate/cost-estimate.component').then(m => m.CostEstimateComponent) },
  { path: 'yaml-diff', title: 'YAML Diff — Kubsome', loadComponent: () => import('./features/yaml-diff/yaml-diff.component').then(m => m.YamlDiffComponent) },
  { path: 'pins', title: 'Pins — Kubsome', loadComponent: () => import('./features/pins/pins.component').then(m => m.PinsComponent) },
  { path: 'watches', title: 'Watches — Kubsome', loadComponent: () => import('./features/watch-manager/watch-manager.component').then(m => m.WatchManagerComponent) },
  { path: 'log-correlation', title: 'Log Correlation — Kubsome', loadComponent: () => import('./features/log-correlation/log-correlation.component').then(m => m.LogCorrelationComponent) },
  { path: 'gateway-monitor', title: 'Gateway — Kubsome', loadComponent: () => import('./features/gateway-monitor/gateway-monitor.component').then(m => m.GatewayMonitorComponent) },
  { path: 'my-dashboard', title: 'Custom Dashboard — Kubsome', loadComponent: () => import('./features/custom-dashboard/custom-dashboard.component').then(m => m.CustomDashboardComponent) },
  { path: 'audit', title: 'Audit — Kubsome', loadComponent: () => import('./features/audit/audit.component').then(m => m.AuditComponent) },
  { path: 'policy', title: 'Policy — Kubsome', loadComponent: () => import('./features/policy/policy.component').then(m => m.PolicyComponent) },
  { path: 'doctor', title: 'Health — Kubsome', loadComponent: () => import('./features/doctor/doctor.component').then(m => m.DoctorComponent) },
  { path: 'schedule', title: 'Schedules — Kubsome', loadComponent: () => import('./features/schedule/schedule.component').then(m => m.ScheduleComponent) },
  { path: 'stats', title: 'Usage Analytics — Kubsome', loadComponent: () => import('./features/stats/stats.component').then(m => m.StatsComponent) },
  { path: 'gitops', title: 'GitOps — Kubsome', loadComponent: () => import('./features/gitops/gitops.component').then(m => m.GitopsComponent) },
  { path: 'mesh', title: 'Service Mesh — Kubsome', loadComponent: () => import('./features/mesh/mesh.component').then(m => m.MeshComponent) },
  { path: 'rightsizing', title: 'Right-Sizing — Kubsome', loadComponent: () => import('./features/rightsizing/rightsizing.component').then(m => m.RightsizingComponent) },
  { path: 'integrations', title: 'Integrations — Kubsome', loadComponent: () => import('./features/integrations/integrations.component').then(m => m.IntegrationsComponent) },
  { path: 'profiles', title: 'Profiles — Kubsome', loadComponent: () => import('./features/profiles/profiles.component').then(m => m.ProfilesComponent) },
  { path: 'analytics', title: 'Analytics — Kubsome', loadComponent: () => import('./features/analytics/analytics.component').then(m => m.AnalyticsComponent) },
];
