import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', title: 'Dashboard — Kubsome', loadComponent: () => import('./features/dashboard/dashboard').then(m => m.DashboardComponent) },
  { path: 'monitor', title: 'Monitor — Kubsome', loadComponent: () => import('./features/monitor/monitor').then(m => m.MonitorComponent) },
  { path: 'pods', title: 'Pods — Kubsome', loadComponent: () => import('./features/pods/pods').then(m => m.PodsComponent) },
  { path: 'events', title: 'Events — Kubsome', loadComponent: () => import('./features/events/events').then(m => m.EventsComponent) },
  { path: 'metrics', title: 'Metrics — Kubsome', loadComponent: () => import('./features/metrics/metrics').then(m => m.MetricsComponent) },
  { path: 'deployments', title: 'Deployments — Kubsome', loadComponent: () => import('./features/deployments/deployments').then(m => m.DeploymentsComponent) },
  { path: 'logs', title: 'Logs — Kubsome', loadComponent: () => import('./features/logs/logs').then(m => m.LogsComponent) },
  { path: 'jobs', title: 'Jobs — Kubsome', loadComponent: () => import('./features/jobs/jobs').then(m => m.JobsComponent) },
  { path: 'namespace', title: 'Namespace — Kubsome', loadComponent: () => import('./features/namespace/namespace').then(m => m.NamespaceComponent) },
  { path: 'rbac', title: 'RBAC — Kubsome', loadComponent: () => import('./features/rbac/rbac').then(m => m.RbacComponent) },
  { path: 'network', title: 'Network — Kubsome', loadComponent: () => import('./features/network/network').then(m => m.NetworkComponent) },
  { path: 'secrets', title: 'Pull Secrets — Kubsome', loadComponent: () => import('./features/secrets/secrets').then(m => m.SecretsComponent) },
  { path: 'incident', title: 'Incident — Kubsome', loadComponent: () => import('./features/incident/incident').then(m => m.IncidentComponent) },
  { path: 'graph', title: 'Service Map — Kubsome', loadComponent: () => import('./features/graph/graph').then(m => m.GraphComponent) },
  { path: 'yaml', title: 'YAML Editor — Kubsome', loadComponent: () => import('./features/yaml-editor/yaml-editor').then(m => m.YamlEditorComponent) },
  { path: 'settings', title: 'Settings — Kubsome', loadComponent: () => import('./features/settings/settings').then(m => m.SettingsComponent) },
  { path: 'compare', title: 'Compare — Kubsome', loadComponent: () => import('./features/compare/compare').then(m => m.CompareComponent) },
  { path: 'timeline', title: 'Timeline — Kubsome', loadComponent: () => import('./features/timeline/timeline').then(m => m.TimelineComponent) },
  { path: 'cost', title: 'Optimization — Kubsome', loadComponent: () => import('./features/cost/cost').then(m => m.CostComponent) },
  { path: 'runbooks', title: 'Runbooks — Kubsome', loadComponent: () => import('./features/runbooks/runbooks').then(m => m.RunbooksComponent) },
  { path: 'search', title: 'Search — Kubsome', loadComponent: () => import('./features/search/search').then(m => m.SearchComponent) },
  { path: 'ai', title: 'AI Assistant — Kubsome', loadComponent: () => import('./features/ai/ai.component').then(m => m.AiComponent) },
  { path: 'terminal', title: 'Terminal — Kubsome', loadComponent: () => import('./features/terminal/terminal').then(m => m.TerminalComponent) },
  { path: 'resources', title: 'Resources — Kubsome', loadComponent: () => import('./features/resources/resources').then(m => m.ResourcesComponent) },
  { path: 'scorecard', title: 'Scorecard — Kubsome', loadComponent: () => import('./features/scorecard/scorecard').then(m => m.ScorecardComponent) },
  { path: 'cost-estimate', title: 'Cost Estimate — Kubsome', loadComponent: () => import('./features/cost-estimate/cost-estimate').then(m => m.CostEstimateComponent) },
  { path: 'yaml-diff', title: 'YAML Diff — Kubsome', loadComponent: () => import('./features/yaml-diff/yaml-diff').then(m => m.YamlDiffComponent) },
  { path: 'pins', title: 'Pins — Kubsome', loadComponent: () => import('./features/pins/pins').then(m => m.PinsComponent) },
  { path: 'watches', title: 'Watches — Kubsome', loadComponent: () => import('./features/watch-manager/watch-manager').then(m => m.WatchManagerComponent) },
  { path: 'log-correlation', title: 'Log Correlation — Kubsome', loadComponent: () => import('./features/log-correlation/log-correlation').then(m => m.LogCorrelationComponent) },
  { path: 'gateway-monitor', title: 'Gateway — Kubsome', loadComponent: () => import('./features/gateway-monitor/gateway-monitor.component').then(m => m.GatewayMonitorComponent) },
  { path: 'my-dashboard', title: 'Custom Dashboard — Kubsome', loadComponent: () => import('./features/custom-dashboard/custom-dashboard').then(m => m.CustomDashboardComponent) },
  { path: 'audit', title: 'Audit — Kubsome', loadComponent: () => import('./features/audit/audit').then(m => m.AuditComponent) },
  { path: 'policy', title: 'Policy — Kubsome', loadComponent: () => import('./features/policy/policy').then(m => m.PolicyComponent) },
  { path: 'doctor', title: 'Health — Kubsome', loadComponent: () => import('./features/doctor/doctor').then(m => m.DoctorComponent) },
  { path: 'schedule', title: 'Schedules — Kubsome', loadComponent: () => import('./features/schedule/schedule').then(m => m.ScheduleComponent) },
  { path: 'stats', title: 'Usage Analytics — Kubsome', loadComponent: () => import('./features/stats/stats').then(m => m.StatsComponent) },
  { path: 'gitops', title: 'GitOps — Kubsome', loadComponent: () => import('./features/gitops/gitops').then(m => m.GitopsComponent) },
  { path: 'mesh', title: 'Service Mesh — Kubsome', loadComponent: () => import('./features/mesh/mesh').then(m => m.MeshComponent) },
  { path: 'rightsizing', title: 'Right-Sizing — Kubsome', loadComponent: () => import('./features/rightsizing/rightsizing').then(m => m.RightsizingComponent) },
  { path: 'integrations', title: 'Integrations — Kubsome', loadComponent: () => import('./features/integrations/integrations').then(m => m.IntegrationsComponent) },
  { path: 'profiles', title: 'Profiles — Kubsome', loadComponent: () => import('./features/profiles/profiles').then(m => m.ProfilesComponent) },
  { path: 'analytics', title: 'Analytics — Kubsome', loadComponent: () => import('./features/analytics/analytics').then(m => m.AnalyticsComponent) },
  { path: 'helm', title: 'Helm — Kubsome', loadComponent: () => import('./features/helm/helm').then(m => m.HelmComponent) },
  { path: 'port-forwards', title: 'Port Forwards — Kubsome', loadComponent: () => import('./features/port-forwards/port-forwards').then(m => m.PortForwardsComponent) },
  { path: 'blast-radius', title: 'Blast Radius — Kubsome', loadComponent: () => import('./features/blast-radius/blast-radius').then(m => m.BlastRadiusComponent) },
  { path: 'health-signals', title: 'Health Signals — Kubsome', loadComponent: () => import('./features/health-signals/health-signals').then(m => m.HealthSignalsComponent) },
  { path: 'chargeback', title: 'Chargeback — Kubsome', loadComponent: () => import('./features/chargeback/chargeback').then(m => m.ChargebackComponent) },
  { path: 'idle-resources', title: 'Idle Resources — Kubsome', loadComponent: () => import('./features/idle-resources/idle-resources').then(m => m.IdleResourcesComponent) },
  { path: 'taints', title: 'Node Taints — Kubsome', loadComponent: () => import('./features/taints/taints').then(m => m.TaintsComponent) },
];
